spring:
  #h2-db url 설정
  datasource:
    url: jdbc:h2:mem:testdb
  #h2-db 설정
  h2:
    console:
      enabled: true
  #jpa 설정
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwtSecret : GoraeJwtToken
jwtExpirationInMs : 604800000