spring:
  #h2-db  설정
#  datasource:
#    url: jdbc:h2:mem:testdb
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:mariadb://localhost:3306/shipment?serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: root
#    password: whosegoods
#    driver-class-name: org.mariadb.jdbc.Driver
  datasource:
    url: jdbc:mariadb://badara.cboaub5k7ggc.ap-northeast-2.rds.amazonaws.com:3306/badara?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: badara
    password: qkekfkgntmrntm
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        ddl-auto: update

jwtSecret : GoraeJwtToken
jwtExpirationInMs : 604800000
